steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "--build-arg"
      - "NODE_ENV=staging"
      - "-t"
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REGISTRY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - apps
      - "-f"
      - apps/docker/Dockerfile.app
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REGISTRY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: bash
    args: [
      '-c',
      'gcloud run deploy "$_SERVICE_NAME"
      --platform=managed
      --image="$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REGISTRY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      --labels="managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID"
      --region="$_DEPLOY_REGION"
      --set-env-vars DATABASE_URL=$$DATABASE_URL_STAGING
      --allow-unauthenticated
      '
    ]
    id: Deploy
    secretEnv: [
      'DATABASE_URL_STAGING',
    ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: bash
    args: [
      '-c',
      'gcloud run jobs create "$_JOB_NAME"
      --image="$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REGISTRY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      --labels="managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID"
      --region="$_DEPLOY_REGION"
      --set-env-vars DATABASE_URL=$$DATABASE_URL_STAGING
      '
    ]
    id: MigrationJob
    secretEnv: [
      'DATABASE_URL_STAGING',
    ]
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REGISTRY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_NUMBER/secrets/database-url-staging-secret/versions/latest
      env: DATABASE_URL_STAGING
substitutions:
  _SERVICE_NAME: todo-staging
  _JOB_NAME: todo-migration-job-staging
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _PLATFORM: managed
  _ARTIFACT_REGISTRY: cloud-run-source-artifact-registry
  _PROJECT_NUMBER: '1022174569886'
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - todo-staging
