name: Deploy Cloudflare Workers with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./pulumi
        run: npm install

      - name: Install Pulumi
        uses: pulumi/actions@v3
        with:
          command: install
          stack-name: dev

      - name: Login to Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: ./pulumi
        run: pulumi login

      - name: Set up Cloudflare environment variables
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PULUMI_CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          PULUMI_CLOUDFLARE_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
        run: echo "Cloudflare environment variables set."

      - name: Pulumi Preview
        working-directory: ./pulumi
        run: pulumi preview
        # run: pulumi preview --stack dev

      - name: Pulumi Up
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: ./pulumi
        run: pulumi up --yes
        # run: pulumi up --yes --stack dev

# name: Pulumi
# on:
#   push:
#     branches:
#       - main
# jobs:
#   update:
#     name: Update
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - uses: actions/checkout@v4
#       # - uses: actions/setup-node@v3.5.0
#       #   with:
#       #     node-version-file: pulumi/package.json
#       - uses: 'google-github-actions/auth@v2'
#         # working-directory: ./pulumi
#         with:
#           project_id: 'develop-436107'
#           workload_identity_provider: 'projects/1022174569886/locations/global/workloadIdentityPools/github-action/providers/github'
#       - uses: cloudflare/pages-action@1
#         with:
#           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           projectName: 'proxy'
#           directory: ./pulumi
#           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
#       - run: npm install
#         working-directory: ./pulumi
#       - uses: pulumi/actions@v3
#         with:
#           command: up
#           stack-name: dev
#           # stack-name: org-name/dev
#           work-dir: ./pulumi
#         env:
#           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}