name: Deploy Cloudflare Workers with Pulumi

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pulumi dependencies
        working-directory: ./pulumi
        run: npm install
      # - name: Install hono dependencies
      #   working-directory: ./proxies
      #   run: npm install

      - name: Install Pulumi CLI
        run: npm install -g @pulumi/pulumi
      - name: Auth with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'develop-436107'
          service_account: 'github-action@develop-436107.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1022174569886/locations/global/workloadIdentityPools/github-action/providers/github'
      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GIT_PAT: ${{ secrets.GIT_PAT }} 

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GIT_PAT: ${{ secrets.GIT_PAT }} 